# Generated by Django 4.1.4 on 2022-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livraria_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livro",
            options={"verbose_name_plural": "Livros"},
        ),
        migrations.AlterField(
            model_name="livro",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, default=99.99, max_digits=7, verbose_name="Valor"
            ),
        ),
    ]
