# Generated by Django 4.1.4 on 2023-01-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sexo',
        ),
    ]
