# Generated by Django 4.1.5 on 2023-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("primeira_app", "0002_alter_livro_options_alter_livro_valor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
